# backend/migrations/script.py.mako
"""schema update

Revision ID: 531b1dea6600
Revises: d3e187e5b03b
Create Date: 2026-02-05 01:04:43.078714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '531b1dea6600'
down_revision = 'd3e187e5b03b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('items_total', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_jobs_last_sync', 'sync_jobs', ['last_sync_at'], unique=False)
    op.create_index('idx_sync_jobs_org_platform', 'sync_jobs', ['organization_id', 'platform'], unique=False)
    op.create_index(op.f('ix_sync_jobs_created_at'), 'sync_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_jobs_organization_id'), 'sync_jobs', ['organization_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_logs_created', 'activity_logs', ['created_at'], unique=False)
    op.create_index('idx_activity_logs_org_action', 'activity_logs', ['organization_id', 'action'], unique=False)
    op.create_index('idx_activity_logs_resource', 'activity_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_organization_id'), 'activity_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_resource_id'), 'activity_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('include_fields', sa.JSON(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_export_jobs_org_status', 'export_jobs', ['organization_id', 'status'], unique=False)
    op.create_index('idx_export_jobs_user', 'export_jobs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_export_jobs_created_at'), 'export_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_export_jobs_organization_id'), 'export_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_user_id'), 'export_jobs', ['user_id'], unique=False)
    op.create_table('conversation_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('completed_fields', sa.JSON(), nullable=True),
    sa.Column('pending_fields', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_stages_candidate_stage', 'conversation_stages', ['candidate_id', 'stage'], unique=True)
    op.create_index('idx_conversation_stages_status', 'conversation_stages', ['status'], unique=False)
    op.create_index(op.f('ix_conversation_stages_candidate_id'), 'conversation_stages', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_conversation_stages_stage'), 'conversation_stages', ['stage'], unique=False)
    op.add_column('candidate_skills', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('candidate_skills', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('candidate_skills', sa.Column('years_experience', sa.Integer(), nullable=True))
    op.add_column('candidate_skills', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('candidate_skills', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('candidate_skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_candidate_skill', 'candidate_skills', type_='unique')
    op.create_index('idx_candidate_skills_candidate', 'candidate_skills', ['candidate_id', 'skill'], unique=True)
    op.create_index('idx_candidate_skills_category', 'candidate_skills', ['category'], unique=False)
    op.create_index('idx_candidate_skills_skill', 'candidate_skills', ['skill'], unique=False)
    op.create_index(op.f('ix_candidate_skills_candidate_id'), 'candidate_skills', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_skills_skill'), 'candidate_skills', ['skill'], unique=False)
    op.add_column('candidates', sa.Column('current_title', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('degree', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('university', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('salary_currency', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('preferred_locations', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('remote_preference', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('candidates', sa.Column('github_url', sa.String(length=500), nullable=True))
    op.add_column('candidates', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('candidate_metadata', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('candidates', 'education',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('candidates', 'status',
               existing_type=postgresql.ENUM('NEW', 'CONTACTED', 'INTERESTED', 'NOT_INTERESTED', 'NEEDS_CLARIFICATION', name='candidate_status_enum'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('candidates', 'overall_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('candidates', 'last_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_candidate_org_owner', table_name='candidates')
    op.drop_constraint('uq_candidate_org_email', 'candidates', type_='unique')
    op.create_index('idx_candidates_email_org', 'candidates', ['email', 'organization_id'], unique=True)
    op.create_index('idx_candidates_org_confidence', 'candidates', ['organization_id', 'overall_confidence'], unique=False)
    op.create_index('idx_candidates_org_status', 'candidates', ['organization_id', 'status'], unique=False)
    op.create_index('idx_candidates_org_updated', 'candidates', ['organization_id', 'updated_at'], unique=False)
    op.create_index('idx_candidates_phone_org', 'candidates', ['phone', 'organization_id'], unique=True)
    op.create_index('idx_candidates_search', 'candidates', ['name', 'email', 'current_company'], unique=False)
    op.create_index(op.f('ix_candidates_created_at'), 'candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_candidates_current_company'), 'candidates', ['current_company'], unique=False)
    op.create_index(op.f('ix_candidates_is_active'), 'candidates', ['is_active'], unique=False)
    op.create_index(op.f('ix_candidates_is_archived'), 'candidates', ['is_archived'], unique=False)
    op.create_index(op.f('ix_candidates_last_message_at'), 'candidates', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_candidates_location'), 'candidates', ['location'], unique=False)
    op.create_index(op.f('ix_candidates_name'), 'candidates', ['name'], unique=False)
    op.create_index(op.f('ix_candidates_organization_id'), 'candidates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_candidates_overall_confidence'), 'candidates', ['overall_confidence'], unique=False)
    op.create_index(op.f('ix_candidates_owner_id'), 'candidates', ['owner_id'], unique=False)
    op.create_index(op.f('ix_candidates_phone'), 'candidates', ['phone'], unique=False)
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    op.create_index(op.f('ix_candidates_updated_at'), 'candidates', ['updated_at'], unique=False)
    op.add_column('jobs', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('assigned_to_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('current_step', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('total_steps', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('error_details', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('timeout_seconds', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('input_data', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('output_data', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.alter_column('jobs', 'type',
               existing_type=postgresql.ENUM('PARSE_RESUME', 'SEND_MESSAGE', 'REPROCESS_RESUME', name='job_type_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=postgresql.ENUM('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='job_status_enum'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('jobs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_job_status_type', table_name='jobs')
    op.create_index('idx_jobs_created_status', 'jobs', ['created_at', 'status'], unique=False)
    op.create_index('idx_jobs_org_status', 'jobs', ['organization_id', 'status'], unique=False)
    op.create_index('idx_jobs_org_type', 'jobs', ['organization_id', 'type'], unique=False)
    op.create_index('idx_jobs_scheduled_status', 'jobs', ['scheduled_for', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_assigned_to_id'), 'jobs', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_jobs_candidate_id'), 'jobs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_jobs_completed_at'), 'jobs', ['completed_at'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_message_id'), 'jobs', ['message_id'], unique=False)
    op.create_index(op.f('ix_jobs_resume_id'), 'jobs', ['resume_id'], unique=False)
    op.create_index(op.f('ix_jobs_scheduled_for'), 'jobs', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_jobs_started_at'), 'jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['assigned_to_id'], ['id'])
    op.drop_column('jobs', 'locked_by')
    op.drop_column('jobs', 'max_attempts')
    op.drop_column('jobs', 'locked_at')
    op.drop_column('jobs', 'attempts')
    op.add_column('messages', sa.Column('message_type', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('template_id', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('platform', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('sentiment', sa.String(length=20), nullable=True))
    op.add_column('messages', sa.Column('hr_approved_by', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('failed_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('failure_reason', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('message_metadata', sa.JSON(), nullable=True))
    op.alter_column('messages', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'DELIVERED', 'FAILED', name='message_status_enum'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('messages', 'classification',
               existing_type=postgresql.ENUM('INTERESTED', 'NOT_INTERESTED', 'NEEDS_CLARIFICATION', 'QUESTION', name='reply_classification_enum'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('messages', 'requires_hr_review',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('messages', 'hr_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('messages', 'hr_approved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_messages_candidate_direction', 'messages', ['candidate_id', 'direction'], unique=False)
    op.create_index('idx_messages_candidate_timestamp', 'messages', ['candidate_id', 'timestamp'], unique=False)
    op.create_index('idx_messages_classification', 'messages', ['classification'], unique=False)
    op.create_index('idx_messages_requires_review', 'messages', ['requires_hr_review', 'hr_approved'], unique=False)
    op.create_index('idx_messages_scheduled', 'messages', ['scheduled_for', 'status'], unique=False)
    op.create_index(op.f('ix_messages_candidate_id'), 'messages', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_messages_classification'), 'messages', ['classification'], unique=False)
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    op.create_index(op.f('ix_messages_hr_approved'), 'messages', ['hr_approved'], unique=False)
    op.create_index(op.f('ix_messages_requires_hr_review'), 'messages', ['requires_hr_review'], unique=False)
    op.create_index(op.f('ix_messages_scheduled_for'), 'messages', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['hr_approved_by'], ['id'])
    op.add_column('organizations', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('settings', sa.JSON(), nullable=True))
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_organizations_created', 'organizations', ['created_at'], unique=False)
    op.create_index('idx_organizations_domain', 'organizations', ['domain'], unique=False)
    op.create_unique_constraint(None, 'organizations', ['domain'])
    op.drop_column('organizations', 'logo')
    op.add_column('parsed_fields', sa.Column('parser_version', sa.String(length=50), nullable=True))
    op.add_column('parsed_fields', sa.Column('extraction_metadata', sa.JSON(), nullable=True))
    op.alter_column('parsed_fields', 'value',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('parsed_fields', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('parsed_fields', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('parsed_fields', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index('ix_parsed_field_candidate_name', table_name='parsed_fields')
    op.create_index('idx_parsed_fields_candidate_name', 'parsed_fields', ['candidate_id', 'name'], unique=True)
    op.create_index('idx_parsed_fields_source', 'parsed_fields', ['source'], unique=False)
    op.create_index(op.f('ix_parsed_fields_candidate_id'), 'parsed_fields', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_parsed_fields_name'), 'parsed_fields', ['name'], unique=False)
    op.add_column('resumes', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('storage_path', sa.String(length=500), nullable=True))
    op.add_column('resumes', sa.Column('text_length', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('resumes', sa.Column('parsing_engine', sa.String(length=50), nullable=True))
    op.add_column('resumes', sa.Column('parsing_version', sa.String(length=50), nullable=True))
    op.add_column('resumes', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('readability_score', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('parsing_confidence', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('is_parsed', sa.Boolean(), nullable=True))
    op.add_column('resumes', sa.Column('has_errors', sa.Boolean(), nullable=True))
    op.add_column('resumes', sa.Column('reprocessed_at', sa.DateTime(), nullable=True))
    op.execute(
        """
        ALTER TABLE resumes
        ALTER COLUMN parse_job_id
        TYPE UUID
        USING parse_job_id::uuid
        """
    )
    op.alter_column('resumes', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('resumes', 'parsed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index('idx_resumes_candidate_uploaded', 'resumes', ['candidate_id', 'uploaded_at'], unique=False)
    op.create_index('idx_resumes_file_type', 'resumes', ['file_type'], unique=False)
    op.create_index('idx_resumes_is_parsed', 'resumes', ['is_parsed'], unique=False)
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_is_parsed'), 'resumes', ['is_parsed'], unique=False)
    op.create_index(op.f('ix_resumes_parsed_at'), 'resumes', ['parsed_at'], unique=False)
    op.create_index(op.f('ix_resumes_uploaded_at'), 'resumes', ['uploaded_at'], unique=False)
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('settings', sa.JSON(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('RECRUITER', 'ADMIN', name='user_role_enum'),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_organization', 'users', ['organization_id'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_unique_constraint('uq_user_email_org', 'users', ['email', 'organization_id'])
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_user_email_org', 'users', type_='unique')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_organization', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('RECRUITER', 'ADMIN', name='user_role_enum'),
               nullable=False)
    op.drop_column('users', 'settings')
    op.drop_column('users', 'last_login')
    op.drop_index(op.f('ix_resumes_uploaded_at'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_parsed_at'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_is_parsed'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_index('idx_resumes_is_parsed', table_name='resumes')
    op.drop_index('idx_resumes_file_type', table_name='resumes')
    op.drop_index('idx_resumes_candidate_uploaded', table_name='resumes')
    op.alter_column('resumes', 'parsed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('resumes', 'uploaded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resumes', 'parse_job_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('resumes', 'reprocessed_at')
    op.drop_column('resumes', 'has_errors')
    op.drop_column('resumes', 'is_parsed')
    op.drop_column('resumes', 'parsing_confidence')
    op.drop_column('resumes', 'readability_score')
    op.drop_column('resumes', 'quality_score')
    op.drop_column('resumes', 'parsing_version')
    op.drop_column('resumes', 'parsing_engine')
    op.drop_column('resumes', 'language')
    op.drop_column('resumes', 'text_length')
    op.drop_column('resumes', 'storage_path')
    op.drop_column('resumes', 'file_size')
    op.drop_index(op.f('ix_parsed_fields_name'), table_name='parsed_fields')
    op.drop_index(op.f('ix_parsed_fields_candidate_id'), table_name='parsed_fields')
    op.drop_index('idx_parsed_fields_source', table_name='parsed_fields')
    op.drop_index('idx_parsed_fields_candidate_name', table_name='parsed_fields')
    op.create_index('ix_parsed_field_candidate_name', 'parsed_fields', ['candidate_id', 'name'], unique=False)
    op.alter_column('parsed_fields', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('parsed_fields', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parsed_fields', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('parsed_fields', 'value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('parsed_fields', 'extraction_metadata')
    op.drop_column('parsed_fields', 'parser_version')
    op.add_column('organizations', sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_index('idx_organizations_domain', table_name='organizations')
    op.drop_index('idx_organizations_created', table_name='organizations')
    op.alter_column('organizations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('organizations', 'updated_at')
    op.drop_column('organizations', 'settings')
    op.drop_column('organizations', 'domain')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_scheduled_for'), table_name='messages')
    op.drop_index(op.f('ix_messages_requires_hr_review'), table_name='messages')
    op.drop_index(op.f('ix_messages_hr_approved'), table_name='messages')
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_index(op.f('ix_messages_classification'), table_name='messages')
    op.drop_index(op.f('ix_messages_candidate_id'), table_name='messages')
    op.drop_index('idx_messages_scheduled', table_name='messages')
    op.drop_index('idx_messages_requires_review', table_name='messages')
    op.drop_index('idx_messages_classification', table_name='messages')
    op.drop_index('idx_messages_candidate_timestamp', table_name='messages')
    op.drop_index('idx_messages_candidate_direction', table_name='messages')
    op.alter_column('messages', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'hr_approved_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('messages', 'hr_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('messages', 'requires_hr_review',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('messages', 'classification',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('INTERESTED', 'NOT_INTERESTED', 'NEEDS_CLARIFICATION', 'QUESTION', name='reply_classification_enum'),
               existing_nullable=True)
    op.alter_column('messages', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PENDING', 'SENT', 'DELIVERED', 'FAILED', name='message_status_enum'),
               nullable=False)
    op.drop_column('messages', 'message_metadata')
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'scheduled_for')
    op.drop_column('messages', 'failure_reason')
    op.drop_column('messages', 'failed_at')
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'delivered_at')
    op.drop_column('messages', 'hr_approved_by')
    op.drop_column('messages', 'sentiment')
    op.drop_column('messages', 'platform')
    op.drop_column('messages', 'template_id')
    op.drop_column('messages', 'message_type')
    op.add_column('jobs', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('locked_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_started_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_scheduled_for'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_resume_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_message_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_completed_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_candidate_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_assigned_to_id'), table_name='jobs')
    op.drop_index('idx_jobs_scheduled_status', table_name='jobs')
    op.drop_index('idx_jobs_org_type', table_name='jobs')
    op.drop_index('idx_jobs_org_status', table_name='jobs')
    op.drop_index('idx_jobs_created_status', table_name='jobs')
    op.create_index('ix_job_status_type', 'jobs', ['status', 'type'], unique=False)
    op.alter_column('jobs', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('jobs', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='job_status_enum'),
               nullable=False)
    op.alter_column('jobs', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PARSE_RESUME', 'SEND_MESSAGE', 'REPROCESS_RESUME', name='job_type_enum'),
               existing_nullable=False)
    op.drop_column('jobs', 'cancelled_at')
    op.drop_column('jobs', 'output_data')
    op.drop_column('jobs', 'input_data')
    op.drop_column('jobs', 'timeout_seconds')
    op.drop_column('jobs', 'scheduled_for')
    op.drop_column('jobs', 'max_retries')
    op.drop_column('jobs', 'retry_count')
    op.drop_column('jobs', 'error_details')
    op.drop_column('jobs', 'total_steps')
    op.drop_column('jobs', 'current_step')
    op.drop_column('jobs', 'assigned_to_id')
    op.drop_column('jobs', 'priority')
    op.drop_index(op.f('ix_candidates_updated_at'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_phone'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_owner_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_overall_confidence'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_organization_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_location'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_last_message_at'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_is_archived'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_is_active'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_current_company'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_created_at'), table_name='candidates')
    op.drop_index('idx_candidates_search', table_name='candidates')
    op.drop_index('idx_candidates_phone_org', table_name='candidates')
    op.drop_index('idx_candidates_org_updated', table_name='candidates')
    op.drop_index('idx_candidates_org_status', table_name='candidates')
    op.drop_index('idx_candidates_org_confidence', table_name='candidates')
    op.drop_index('idx_candidates_email_org', table_name='candidates')
    op.create_unique_constraint('uq_candidate_org_email', 'candidates', ['organization_id', 'email'])
    op.create_index('ix_candidate_org_owner', 'candidates', ['organization_id', 'owner_id'], unique=False)
    op.alter_column('candidates', 'last_message_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('candidates', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('candidates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'overall_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('candidates', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('NEW', 'CONTACTED', 'INTERESTED', 'NOT_INTERESTED', 'NEEDS_CLARIFICATION', name='candidate_status_enum'),
               nullable=False)
    op.alter_column('candidates', 'education',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('candidates', 'deleted_at')
    op.drop_column('candidates', 'is_archived')
    op.drop_column('candidates', 'is_active')
    op.drop_column('candidates', 'candidate_metadata')
    op.drop_column('candidates', 'tags')
    op.drop_column('candidates', 'source')
    op.drop_column('candidates', 'github_url')
    op.drop_column('candidates', 'linkedin_url')
    op.drop_column('candidates', 'remote_preference')
    op.drop_column('candidates', 'preferred_locations')
    op.drop_column('candidates', 'salary_currency')
    op.drop_column('candidates', 'timezone')
    op.drop_column('candidates', 'country')
    op.drop_column('candidates', 'city')
    op.drop_column('candidates', 'graduation_year')
    op.drop_column('candidates', 'university')
    op.drop_column('candidates', 'degree')
    op.drop_column('candidates', 'current_title')
    op.drop_index(op.f('ix_candidate_skills_skill'), table_name='candidate_skills')
    op.drop_index(op.f('ix_candidate_skills_candidate_id'), table_name='candidate_skills')
    op.drop_index('idx_candidate_skills_skill', table_name='candidate_skills')
    op.drop_index('idx_candidate_skills_category', table_name='candidate_skills')
    op.drop_index('idx_candidate_skills_candidate', table_name='candidate_skills')
    op.create_unique_constraint('uq_candidate_skill', 'candidate_skills', ['candidate_id', 'skill'])
    op.alter_column('candidate_skills', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidate_skills', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('candidate_skills', 'updated_at')
    op.drop_column('candidate_skills', 'years_experience')
    op.drop_column('candidate_skills', 'source')
    op.drop_column('candidate_skills', 'category')
    op.drop_index(op.f('ix_conversation_stages_stage'), table_name='conversation_stages')
    op.drop_index(op.f('ix_conversation_stages_candidate_id'), table_name='conversation_stages')
    op.drop_index('idx_conversation_stages_status', table_name='conversation_stages')
    op.drop_index('idx_conversation_stages_candidate_stage', table_name='conversation_stages')
    op.drop_table('conversation_stages')
    op.drop_index(op.f('ix_export_jobs_user_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_organization_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_created_at'), table_name='export_jobs')
    op.drop_index('idx_export_jobs_user', table_name='export_jobs')
    op.drop_index('idx_export_jobs_org_status', table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_resource_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_organization_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_index('idx_activity_logs_resource', table_name='activity_logs')
    op.drop_index('idx_activity_logs_org_action', table_name='activity_logs')
    op.drop_index('idx_activity_logs_created', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_sync_jobs_organization_id'), table_name='sync_jobs')
    op.drop_index(op.f('ix_sync_jobs_created_at'), table_name='sync_jobs')
    op.drop_index('idx_sync_jobs_org_platform', table_name='sync_jobs')
    op.drop_index('idx_sync_jobs_last_sync', table_name='sync_jobs')
    op.drop_table('sync_jobs')
    # ### end Alembic commands ###