# backend/migrations/script.py.mako
"""add work_experience table

Revision ID: 789ae706878e
Revises: 531b1dea6600
Create Date: 2026-02-07 12:19:09.312991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789ae706878e'
down_revision = '531b1dea6600'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_experience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experience_candidate_id'), 'work_experience', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_experience_candidate_id'), table_name='work_experience')
    op.drop_table('work_experience')
    # ### end Alembic commands ###