# backend/migrations/script.py.mako
"""fix updated_at default behavior

Revision ID: d3e187e5b03b
Revises: 2c744d519e76
Create Date: 2026-02-04 16:31:58.390778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e187e5b03b'
down_revision = '2c744d519e76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###